package com.company.NetSDK;

import java.io.Serializable;

public class NET_MONITORWALL_OPERATE_TYPE implements Serializable {
	private static final long serialVersionUID = 1L;
	
	public static final int 	NET_MONITORWALL_OPERATE_ADD = 0;            // Lm<S5gJSG=, 6TS& NET_IN_MONITORWALL_ADD :M NET_OUT_MONITORWALL_ADD
	public static final int    NET_MONITORWALL_OPERATE_CTRL_TOUR = 1;      // T$08BVQ2?XVF, 6TS& NET_IN_CTRL_COLLECTIONTOUR :M  NET_OUT_CTRL_COLLECTIONTOUR
	public static final int    NET_MONITORWALL_OPERATE_GET_STATUS = 2;     // ;qH!>XUs51G0W4L,, 6TS& NET_IN_MONITORWALL_GET_STATUS :M  NET_OUT_MONITORWALL_GET_STATUS
	public static final int    NET_MONITORWALL_OPERATE_SET_COLL_SCHD = 3;  // IhVCT$08J1<d1m, 6TS& NET_IN_MONITORWALL_SET_COLL_SCHD :M NET_OUT_MONITORWALL_SET_COLL_SCHD
	public static final int    NET_MONITORWALL_OPERATE_GET_COLL_SCHD = 4;  // ;qH!T$08J1<d1m, 6TS& NET_IN_MONITORWALL_GET_COLL_SCHD :M NET_OUT_MONITORWALL_GET_COLL_SCHD
	public static final int    NET_MONITORWALL_OPERATE_REMOVE = 5;         // I>3}5gJSG=, 6TS& NET_IN_MONITORWALL_REMOVE :M NET_OUT_MONITORWALL_REMOVE
	public static final int    NET_MONITORWALL_OPERATE_SET_ENABLE = 6;     // IhVCJ9D\, 6TS& NET_IN_MONITORWALL_SET_ENABLE :M NET_OUT_MONITORWALL_SET_ENABLE
	public static final int    NET_MONITORWALL_OPERATE_GET_ENABLE = 7;     // ;qH!J9D\, 6TS& NET_IN_MONITORWALL_GET_ENABLE :M NET_OUT_MONITORWALL_GET_ENABLE
	public static final int    NET_MONITORWALL_OPERATE_NAME_EXIST = 8;     // 5gJSG=JG7q4fTZ, 6TS& NET_IN_MONITORWALL_NAME_EXIST :M NET_OUT_MONITORWALL_NAME_EXIST

}
