package com.company.NetSDK;

import java.io.Serializable;

public class NET_SPLIT_OPERATE_TYPE implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	public static final int NET_SPLIT_OPERATE_SET_BACKGROUND = 0;          // IhVC13>0M<F,, 6TS& NET_IN_SPLIT_SET_BACKGROUND :M NET_OUT_SPLIT_SET_BACKBROUND
	public static final int NET_SPLIT_OPERATE_GET_BACKGROUND = 1;           // ;qH!13>0M<F,, 6TS& NET_IN_SPLIT_GET_BACKGROUND :M NET_OUT_SPLIT_GET_BACKGROUND
	public static final int NET_SPLIT_OPERATE_SET_PREPULLSRC = 2;           // IhVCT$@-AwT4, 6TS& NET_IN_SPLIT_SET_PREPULLSRC :M NET_OUT_SPLIT_SET_PREPULLSRC
	public static final int NET_SPLIT_OPERATE_SET_HIGHLIGHT = 3;            // IhVCT41_?r8_AAJ9D\?*9X, 6TS& NET_IN_SPLIT_SET_HIGHLIGHT :M NET_OUT_SPLIT_SET_HIGHLIGHT
	public static final int NET_SPLIT_OPERATE_SET_ZORDER = 4;              // 5wU{40?ZZPr, 6TS& NET_IN_SPLIT_SET_ZORDER :M NET_OUT_SPLIT_SET_ZORDER
	public static final int NET_SPLIT_OPERATE_SET_TOUR = 5;                // 40?ZBVQ2?XVF, 6TS& NET_IN_SPLIT_SET_TOUR :M NET_OUT_SPLIT_SET_TOUR
	public static final int NET_SPLIT_OPERATE_GET_TOUR_STATUS = 6;          // ;qH!40?ZBVQ2W4L,, 6TS& NET_IN_SPLIT_GET_TOUR_STATUS :M NET_OUT_SPLIT_GET_TOUR_STATUS
	public static final int NET_SPLIT_OPERATE_GET_SCENE = 7;               // ;qH!FADZ40?ZPEO", 6TS& NET_IN_SPLIT_GET_SCENE :M NET_OUT_SPLIT_GET_SCENE
	public static final int NET_SPLIT_OPERATE_OPEN_WINDOWS = 8;             // EzA??*40, 6TS& NET_IN_SPLIT_OPEN_WINDOWS :M NET_OUT_SPLIT_OPEN_WINDOWS
	public static final int NET_SPLIT_OPERATE_SET_WORK_MODE = 9;          // IhVC9$WwD#J=, 6TS& NET_IN_SPLIT_SET_WORK_MODE :M NET_OUT_SPLIT_SET_WORK_MODE
	public static final int NET_SPLIT_OPERATE_GET_PLAYER = 10;              // ;qH!2%7EFwJ5@},6TS& NET_IN_SPLIT_GET_PLAYER :M NET_OUT_SPLIT_GET_PLAYER
	public static final int NET_WM_OPERATE_SET_WORK_MODE = 11;            // IhVC40?Z9$WwD#J=,6TS& NET_IN_WM_SET_WORK_MODE :M NET_OUT_WM_SET_WORK_MODE
	public static final int NET_WM_OPERATE_GET_WORK_MODE = 12;              // ;qH!40?Z9$WwD#J=,6TS& NET_IN_WM_GET_WORK_MODE :M NET_OUT_WM_GET_WORK_MODE
	public static final int NET_SPLIT_OPERATE_CLOSE_WINDOWS = 13;           // EzA?9X40, 6TS& NET_IN_SPLIT_CLOSE_WINDOWS :M NET_OUT_SPLIT_CLOSE_WINDOWS
	public static final int NET_WM_OPERATE_SET_FISH_EYE_PARAM = 14;        // IhVCJd3vFA5DScQ[=CU}9fTr , 6TS& NET_IN_WM_SET_FISH_EYE_PARAM :M NET_OUT_WM_SET_FISH_EYE_PARAM
	public static final int NET_WM_OPERATE_SET_CORRIDOR_MODE = 15;		// IhVC40?ZW_@HD#J=#,6TS&NET_IN_WM_SET_CORRIDOR_MODE:MNET_OUT_WM_SET_CORRIDOR_MODE
	public static final int NET_WM_OPERATE_GET_CORRIDOR_MODE = 16;			// ;qH!40?ZW_@HD#J=#,6TS&NET_IN_WM_GET_CORRIDOR_MODE:MNET_OUT_WM_GET_CORRIDOR_MODE
	
}
